/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tictactoe.frame;

import com.tictactoe.TicTacToe;
import com.tictactoe.utility.MyButtonGroup;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author BuenSeñor
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        card = (CardLayout) cardPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGame = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        optionPanel = new javax.swing.JPanel();
        btnPlayer = new javax.swing.JButton();
        btnPlayerCPU = new javax.swing.JButton();
        btnCPU = new javax.swing.JButton();
        gamePanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        lblTurn = new javax.swing.JLabel();
        lblMode = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblO = new javax.swing.JLabel();
        tictactoePanel = new javax.swing.JPanel();
        btnX0Y0 = new javax.swing.JButton();
        btnX0Y1 = new javax.swing.JButton();
        btnX0Y2 = new javax.swing.JButton();
        btnX1Y0 = new javax.swing.JButton();
        btnX1Y1 = new javax.swing.JButton();
        btnX1Y2 = new javax.swing.JButton();
        btnX2Y0 = new javax.swing.JButton();
        btnX2Y1 = new javax.swing.JButton();
        btnX2Y2 = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lblTitle.setText("Tic Tac Toe");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardPanel.setLayout(new java.awt.CardLayout());

        optionPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnPlayer.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnPlayer.setText("Player vs Player");
        btnPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerActionPerformed(evt);
            }
        });

        btnPlayerCPU.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnPlayerCPU.setText("Player vs CPU");
        btnPlayerCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerCPUActionPerformed(evt);
            }
        });

        btnCPU.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnCPU.setText("CPU vs CPU");
        btnCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnPlayerCPU, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(btnCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(100, 100, 100))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(btnPlayer)
                .addGap(18, 18, 18)
                .addComponent(btnPlayerCPU)
                .addGap(18, 18, 18)
                .addComponent(btnCPU)
                .addGap(46, 46, 46))
        );

        cardPanel.add(optionPanel, "option");

        gamePanel.setBackground(new java.awt.Color(255, 255, 255));

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTurn.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblTurn.setText(" ");
        lblTurn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turn:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 11))); // NOI18N
        lblTurn.setFocusable(false);

        lblMode.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblMode.setText(" ");
        lblMode.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 11))); // NOI18N

        lblX.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblX.setText(" ");
        lblX.setBorder(javax.swing.BorderFactory.createTitledBorder("X"));

        lblO.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblO.setText(" ");
        lblO.setBorder(javax.swing.BorderFactory.createTitledBorder("O"));

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMode, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(lblTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTurn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tictactoePanel.setBackground(new java.awt.Color(255, 255, 255));

        btnX0Y0.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnGroupGame.add(btnX0Y0);
        btnX0Y0.setPreferredSize(new java.awt.Dimension(47, 47));
        btnX0Y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX0Y0ActionPerformed(evt);
            }
        });

        btnX0Y1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnGroupGame.add(btnX0Y1);
        btnX0Y1.setPreferredSize(new java.awt.Dimension(47, 47));
        btnX0Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX0Y1ActionPerformed(evt);
            }
        });

        btnX0Y2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnGroupGame.add(btnX0Y2);
        btnX0Y2.setPreferredSize(new java.awt.Dimension(47, 47));
        btnX0Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX0Y2ActionPerformed(evt);
            }
        });

        btnX1Y0.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnGroupGame.add(btnX1Y0);
        btnX1Y0.setPreferredSize(new java.awt.Dimension(47, 47));
        btnX1Y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX1Y0ActionPerformed(evt);
            }
        });

        btnX1Y1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnGroupGame.add(btnX1Y1);
        btnX1Y1.setPreferredSize(new java.awt.Dimension(47, 47));
        btnX1Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX1Y1ActionPerformed(evt);
            }
        });

        btnX1Y2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnGroupGame.add(btnX1Y2);
        btnX1Y2.setPreferredSize(new java.awt.Dimension(47, 47));
        btnX1Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX1Y2ActionPerformed(evt);
            }
        });

        btnX2Y0.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnGroupGame.add(btnX2Y0);
        btnX2Y0.setPreferredSize(new java.awt.Dimension(47, 47));
        btnX2Y0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2Y0ActionPerformed(evt);
            }
        });

        btnX2Y1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnGroupGame.add(btnX2Y1);
        btnX2Y1.setPreferredSize(new java.awt.Dimension(47, 47));
        btnX2Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2Y1ActionPerformed(evt);
            }
        });

        btnX2Y2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnGroupGame.add(btnX2Y2);
        btnX2Y2.setPreferredSize(new java.awt.Dimension(47, 47));
        btnX2Y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2Y2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tictactoePanelLayout = new javax.swing.GroupLayout(tictactoePanel);
        tictactoePanel.setLayout(tictactoePanelLayout);
        tictactoePanelLayout.setHorizontalGroup(
            tictactoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tictactoePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tictactoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tictactoePanelLayout.createSequentialGroup()
                        .addComponent(btnX0Y0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX1Y0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX2Y0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tictactoePanelLayout.createSequentialGroup()
                        .addComponent(btnX0Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX1Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX2Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tictactoePanelLayout.createSequentialGroup()
                        .addComponent(btnX0Y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX1Y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX2Y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tictactoePanelLayout.setVerticalGroup(
            tictactoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tictactoePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tictactoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnX0Y0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnX1Y0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnX2Y0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tictactoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnX0Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnX1Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnX2Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tictactoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnX0Y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnX1Y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnX2Y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMenu.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tictactoePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnMenu)))
                .addGap(18, 18, 18)
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addComponent(tictactoePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMenu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardPanel.add(gamePanel, "game");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Show the Game Panel, set the new game mode as 'Player vs Player'.
     * Initialize a new TicTacToe object.
     *
     * @param evt
     */
    private void btnPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerActionPerformed
        card.show(cardPanel, "game");
        t3 = new TicTacToe(btnX0Y0, btnX1Y0, btnX2Y0, btnX0Y1, btnX1Y1, btnX2Y1, btnX0Y2, btnX1Y2, btnX2Y2);
        lblMode.setText(TicTacToe.PVP);
        lblTurn.setText(TicTacToe.PLAYER_1);
        lblX.setText(TicTacToe.PLAYER_1);
        lblO.setText(TicTacToe.PLAYER_2);
    }//GEN-LAST:event_btnPlayerActionPerformed

    /**
     * Show the Game Panel, set the new game mode as 'Player vs CPU'. Initialize
     * a new TicTacToe object.
     *
     * @param evt
     */
    private void btnPlayerCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerCPUActionPerformed
//        card.show(cardPanel, "game");
//        t3 = new TicTacToe(btnX0Y0, btnX1Y0, btnX2Y0, btnX0Y1, btnX1Y1, btnX2Y1, btnX0Y2, btnX1Y2, btnX2Y2);
//        t3.setMode(TicTacToe.PVC);
    }//GEN-LAST:event_btnPlayerCPUActionPerformed

    /**
     * Show the Game Panel, set the new game mode as 'CPU vs CPU'. Initialize a
     * new TicTacToe object.
     *
     * @param evt
     */
    private void btnCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPUActionPerformed
//        card.show(cardPanel, "game");
//        t3 = new TicTacToe(btnX0Y0, btnX1Y0, btnX2Y0, btnX0Y1, btnX1Y1, btnX2Y1, btnX0Y2, btnX1Y2, btnX2Y2);
//        t3.setMode(TicTacToe.CVC);
    }//GEN-LAST:event_btnCPUActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        clearAll();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnX0Y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX0Y0ActionPerformed
        playerMoviment(0, 0);
    }//GEN-LAST:event_btnX0Y0ActionPerformed

    private void btnX1Y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX1Y0ActionPerformed
        playerMoviment(1, 0);
    }//GEN-LAST:event_btnX1Y0ActionPerformed

    private void btnX2Y0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2Y0ActionPerformed
        playerMoviment(2, 0);
    }//GEN-LAST:event_btnX2Y0ActionPerformed

    private void btnX0Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX0Y1ActionPerformed
        playerMoviment(0, 1);
    }//GEN-LAST:event_btnX0Y1ActionPerformed

    private void btnX1Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX1Y1ActionPerformed
        playerMoviment(1, 1);
    }//GEN-LAST:event_btnX1Y1ActionPerformed

    private void btnX2Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2Y1ActionPerformed
        playerMoviment(2, 1);
    }//GEN-LAST:event_btnX2Y1ActionPerformed

    private void btnX0Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX0Y2ActionPerformed
        playerMoviment(0, 2);
    }//GEN-LAST:event_btnX0Y2ActionPerformed

    private void btnX1Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX1Y2ActionPerformed
        playerMoviment(1, 2);
    }//GEN-LAST:event_btnX1Y2ActionPerformed

    private void btnX2Y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2Y2ActionPerformed
        playerMoviment(2, 2);
    }//GEN-LAST:event_btnX2Y2ActionPerformed

    private void clearAll(){
        card.show(cardPanel, "option");
        lblMode.setText("");
        lblTurn.setText("");
        lblO.setText("");
        lblX.setText("");
        MyButtonGroup.setText("", btnGroupGame);
    }
    
    private void playerMoviment(int x, int y){
        if(t3.isEmpty(x, y)){
            if(lblX.getText().equals(lblTurn.getText())){
                t3.setCoordenate(x, y, TicTacToe.CHAR_X);
            }else{
                t3.setCoordenate(x, y, TicTacToe.CHAR_O);
            }
            t3.incrementCount();
            if(lblTurn.getText().equals(lblX.getText())){
                if(t3.win(TicTacToe.CHAR_X)){
                    JOptionPane.showMessageDialog(this, lblTurn.getText()+" win!", "WIN", 1);
                    clearAll();
                }
            }else{
                if(t3.win(TicTacToe.CHAR_O)){
                    JOptionPane.showMessageDialog(this, lblTurn.getText()+" win!", "WIN", 1);
                    clearAll();
                }
            }
            if(t3.getCount()==9){
                JOptionPane.showMessageDialog(this, "Tie", "TIE", 1);
                clearAll();
            }
            if(lblTurn.getText().equals(lblX.getText())){
                lblTurn.setText(lblO.getText());
            }else{
                lblTurn.setText(lblX.getText());
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private CardLayout card;
    private TicTacToe t3;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCPU;
    private javax.swing.ButtonGroup btnGroupGame;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPlayer;
    private javax.swing.JButton btnPlayerCPU;
    private javax.swing.JButton btnX0Y0;
    private javax.swing.JButton btnX0Y1;
    private javax.swing.JButton btnX0Y2;
    private javax.swing.JButton btnX1Y0;
    private javax.swing.JButton btnX1Y1;
    private javax.swing.JButton btnX1Y2;
    private javax.swing.JButton btnX2Y0;
    private javax.swing.JButton btnX2Y1;
    private javax.swing.JButton btnX2Y2;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel lblMode;
    private javax.swing.JLabel lblO;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTurn;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel tictactoePanel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
